version: '3.8'

services:
  mysqlignite:
    image: mysql:latest
    container_name: mysqlignite
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: docker
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data: